# Generated by Django 5.0 on 2024-01-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevConnect', '0002_alter_chat_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevConnect.genre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevConnect.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.ManyToManyField(related_name='projects', through='DevConnect.ProjectGenre', to='DevConnect.genre'),
        ),
    ]
