# Generated by Django 5.0 on 2024-01-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevConnect', '0002_customuser_alter_project_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_password',
        ),
    ]
