# Generated by Django 5.0 on 2024-01-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevConnect', '0003_remove_customuser_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
